### PR TITLE
Add JW Player segtax

### PR DESCRIPTION
**Pull request by karimMourra**
This PR is a request for a a taxonomy ID to be assigned to JW Player in the segtax community extension list.

### CODE REVIEW

**Comment by karimMourra** [comment]
@amitshetty @bjd326

**Comment by amitshetty** [comment]
I know it is a bit confusing since the note says 500+, but I think the plan was to start from 501 (which is why Iris is at 501 :-) ) 
Recommend you use 502 for this entry.
Thanks!

**Comment by karimMourra** [comment]
@amitshetty updated

**Comment by amitshetty** [comment]
Done. @bjd326 - fyi.

**Pull request merged**
