### PR TITLE
SCID.md word correction

### PR DESCRIPTION
**Pull request by yowcow**
The spec is for a response

### CODE REVIEW

**Comment by amitshetty** [comment]
@anderagakura - can you take a look?

**Comment by anderagakura** [comment]
> The spec is for a response

@amitshetty Thanks for notifying me

@yowcow  So regarding the spec, I wanted to follow the [Github process/status](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews) which is when you propose something, it's identified as a "request change". I agree with you, the change is about the bid response and "response change" sounds better but it seems to be a request change. And that's why I specify [this request change is about the a bid response](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews)

**Comment by amitshetty** [comment]
@anderagakura  - I think the github process is a different thing. That is a request for a change. 
Here this is within the doc, and is about a bid response. I think we should make the change.

**Comment by amitshetty** [comment]
Actually, I will just change it a bit more so there is no confusion. I will just call it "Changes".

**Pull request merged**
