### PR TITLE
Added use of alternatives to GLN as Advertiser ID

### PR DESCRIPTION
**Pull request by anderagakura**

### CODE REVIEW

**Comment by amitshetty** [comment]
@anderagakura  - is there anyone who can review this before we merge it in? I dont have enough context to do so.

**Comment by anderagakura** [comment]
We had a discussion with the group and as all the advertisers and countries are not part of the GLN database, the conclusion is to allow alternatives identifiers as long as those remains unique to a given advertiser.

@jdelhommeau Could you please have a look on it? Thanks

**Comment by jdelhommeau** [comment]
looks good to me.

**Comment by amitshetty** [comment]
ok, merging. Thanks!

**Pull request merged**
