### PR TITLE
Add Trust.id

### PR DESCRIPTION
**Pull request by anderagakura**

### CODE REVIEW

**Comment by amitshetty** [comment]
Will review some more, but first comment - I'd recommend moving the contents of the docs (that make sense) here to github rather than pointing to a google doc.

**Comment by anderagakura** [comment]
@amitshetty In which folder can I move the content?

**Comment by amitshetty** [comment]
> @amitshetty In which folder can I move the content?

Sorry - by move I meant convert to markdown and include in this file. :-) 
If images need to be moved here, maybe we can create an assets folder and point to there?

**Comment by anderagakura** [comment]
> > @amitshetty In which folder can I move the content?
> 
> Sorry - by move I meant convert to markdown and include in this file. :-)
> If images need to be moved here, maybe we can create an assets folder and point to there?

On my side, I merged the two files in only one markdown file. Could you please create a folder to allow to push the pictures? And then I will push the final markdown file.

**Comment by amitshetty** [comment]
Apologies for the delay - I added a folder called assets

**Pull request merged**
