### PR TITLE
Add Audigent Taxonomy ID Range

### PR DESCRIPTION
**Pull request by anthonylauzon**
This PR is a request for a a taxonomy ID range to be assigned to Audigent in the segtax community extension list.  The format reflects where we arrived at  in https://github.com/prebid/Prebid.js/issues/6057 along with the various discussions both in the OpenRTB 2.6 and Prebid Taxonomy meetings.  We will be working with supply and demand platforms to distribute definitions for and enable these taxonomies in the coming weeks.

### CODE REVIEW

**Comment by anthonylauzon** [comment]
@amitshetty @bjd326 as discussed during previous calls

**Comment by amitshetty** [comment]
I guess my only q is do we need to reserve ids for test taxonomies. If they really are for testing, cant they be done with some really high numbers that dont need to be listed here? After all, all the parties involved in the test would know what is coming in - right?

**Comment by anthonylauzon** [comment]
"Test" is kind of a misnomer. These taxonomies would be similar to the private audience and contextual taxonomies, but expected to change more frequently. Elements of them might make their way into successive versions of the audience and contextual taxonomies.

**Comment by amitshetty** [comment]
Ah - makes sense. 
Since this is the first of these, let me circle with Ben and confirm before merging it in.

**Comment by anthonylauzon** [comment]
thank you @amitshetty

**Pull request merged**
